1. Retention Analysis:

-- Employees who LEFT
SELECT COUNT(*) AS EmployeesLeft
FROM Employee
WHERE TerminationYear IS NOT NULL;


-- Employees RETAINED
SELECT COUNT(*) AS EmployeesRetained
FROM Employee
WHERE TerminationYear IS NULL;

-------------
--Retention Rate for Each Department
SELECT 
    d.DepartmentName,
    SUM(CASE WHEN e.TerminationYear IS NULL THEN 1 ELSE 0 END) AS Retained,
    SUM(CASE WHEN e.TerminationYear IS NOT NULL THEN 1 ELSE 0 END) AS NotRetained,
    COUNT(*) AS TotalEmployees,
    CAST(SUM(CASE WHEN e.TerminationYear IS NULL THEN 1 ELSE 0 END) * 100.0 
         / COUNT(*) AS DECIMAL(5,2)) AS RetentionRate
FROM Employee e
JOIN Department d ON e.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName
ORDER BY RetentionRate DESC;

------------------------
--Which department performs the best?

--(the performance metric: Base pay, total pay, overtime, cost efficiency, etc.)
-----
---Total Earnings Generated by Departments


SELECT
    d.DepartmentName,
    SUM(
        COALESCE(e.BaseGrossPay, 0) +
        COALESCE(e.OvertimeGrossPay, 0) +
        COALESCE(e.LongevityGrossPay, 0) +
        COALESCE(e.PostSeparationGrossPay, 0) +
        COALESCE(e.MiscellaneousGrossPay, 0)
    ) AS TotalDeptEarnings
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
JOIN Department d ON emp.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName
ORDER BY TotalDeptEarnings DESC;


---------------

---Employees with highest absences by using employee id

SELECT TOP 10
    emp.EmployeeID,
    emp.FirstName,
    emp.LastName,
    COUNT(e.AbsenceID) AS AbsenceCount
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
WHERE e.AbsenceID IS NOT NULL
GROUP BY emp.EmployeeID, emp.FirstName, emp.LastName
ORDER BY AbsenceCount DESC;

-------------------
---Employees with highest absences by using public id
SELECT TOP 10
    emp.PublicID,
    emp.FirstName,
    emp.LastName,
    COUNT(e.AbsenceID) AS AbsenceCount
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
WHERE e.AbsenceID IS NOT NULL
GROUP BY emp.PublicID, emp.FirstName, emp.LastName
ORDER BY AbsenceCount DESC;

----------------------------------

---WHY these employees have high absences?
--without department name
SELECT
    emp.PublicID,
    emp.FirstName,
    emp.LastName,
    c.Season,
    COUNT(e.AbsenceID) AS AbsenceCount
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
JOIN Calendar c ON e.CalendarID = c.CalendarID
WHERE e.AbsenceID IS NOT NULL
  AND emp.PublicID IN (7088, 10360, 13089, 18702)  -- top 4 employees
GROUP BY
    emp.PublicID, emp.FirstName, emp.LastName, c.Season
ORDER BY
    emp.PublicID, AbsenceCount DESC;

	---------------------------
---by department name	

SELECT
    emp.PublicID,
    emp.FirstName,
    emp.LastName,
    d.DepartmentName,
    c.Season,
    COUNT(e.AbsenceID) AS AbsenceCount
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
JOIN Department d ON emp.DepartmentID = d.DepartmentID
JOIN Calendar c ON e.CalendarID = c.CalendarID
WHERE e.AbsenceID IS NOT NULL
  AND emp.PublicID IN (7088, 10360, 13089, 18702)  -- top 4
GROUP BY emp.PublicID, emp.FirstName, emp.LastName,
         d.DepartmentName, c.Season
ORDER BY emp.PublicID, AbsenceCount DESC;

-------How is Absence related to earnings?

USE Project_Team6;
GO

SELECT
    emp.PublicID,
    emp.FirstName,
    emp.LastName,

    -- Total absences
    SUM(
        CASE 
            WHEN e.AbsenceID IS NOT NULL THEN 1 
            ELSE 0 
        END
    ) AS TotalAbsences,

    -- Total earnings
    SUM(
        COALESCE(e.BaseGrossPay, 0) +
        COALESCE(e.OvertimeGrossPay, 0) +
        COALESCE(e.LongevityGrossPay, 0) +
        COALESCE(e.PostSeparationGrossPay, 0) +
        COALESCE(e.MiscellaneousGrossPay, 0)
    ) AS TotalEarnings
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
GROUP BY emp.PublicID, emp.FirstName, emp.LastName
ORDER BY TotalAbsences DESC;

--------------------
---Which departments perform best financially?

SELECT
    d.DepartmentName,
    SUM(
        COALESCE(e.BaseGrossPay, 0) +
        COALESCE(e.OvertimeGrossPay, 0) +
        COALESCE(e.LongevityGrossPay, 0) +
        COALESCE(e.PostSeparationGrossPay, 0) +
        COALESCE(e.MiscellaneousGrossPay, 0)
    ) AS TotalDeptEarnings
FROM Earnings e
JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
JOIN Department d ON emp.DepartmentID = d.DepartmentID
GROUP BY d.DepartmentName
ORDER BY TotalDeptEarnings DESC;






-- Trigger: subtract $50 for unapproved absence codes
CREATE TRIGGER trg_LatePenalty
ON Earnings
AFTER INSERT
AS
BEGIN
    UPDATE e
    SET e.MiscellaneousGrossPay =
        COALESCE(e.MiscellaneousGrossPay, 0) - 50
    FROM Earnings e
    JOIN inserted i ON e.EarningsID = i.EarningsID
    JOIN Absence a ON i.AbsenceID = a.AbsenceID
    WHERE a.Reason IN (21, 23, 26);  -- selected reason code to apply penalty
END;
GO

--Change reason code
ALTER TRIGGER trg_LatePenalty
ON Earnings
AFTER INSERT
AS
BEGIN
    UPDATE e
    SET e.MiscellaneousGrossPay =
        COALESCE(e.MiscellaneousGrossPay, 0) - 50
    FROM Earnings e
    JOIN inserted i ON e.EarningsID = i.EarningsID
    JOIN Absence a ON i.AbsenceID = a.AbsenceID
    WHERE a.Reason IN (0, 26);   --selected reason code to apply penalty
END;
GO




SELECT * FROM Earnings
SELECT * FROM Absence


---- TESTING THE TRIGGER:
-- Insert a row with AbsenceID = NULL -- No penalty

INSERT INTO Earnings (
    EmployeeID, CalendarID, AbsenceID,
    OvertimeGrossPay, BaseGrossPay, LongevityGrossPay,
    PostSeparationGrossPay, MiscellaneousGrossPay
)
VALUES (1, 1, 3, 50, 200, 0, 0, 100);  -- absence id 3 is under reason code 9 that's why no penalty applied

SELECT TOP 1 * FROM Earnings ORDER BY EarningsID DESC;


--Insert a row with AbsenceID = value -- penalty applied
INSERT INTO Earnings (
    EmployeeID, CalendarID, AbsenceID,
    OvertimeGrossPay, BaseGrossPay, LongevityGrossPay,
    PostSeparationGrossPay, MiscellaneousGrossPay
)
VALUES (1, 1, 6, 50, 200, 0, 0, 100);  -- absence id 6 is under reason code 26 that's why penalty applied


SELECT TOP 1 * FROM Earnings ORDER BY EarningsID DESC;





-- STORED PROCEDURE: sp_GetMonthlyPayroll
-- Returns payroll for a given YEAR and QUARTER
CREATE PROCEDURE sp_Employee_Payroll
    @Year INT,
    @Quarter INT
AS
BEGIN
    SELECT
        emp.EmployeeID,
        emp.FirstName,
        emp.LastName,
        SUM(
            COALESCE(e.BaseGrossPay,0) +
            COALESCE(e.OvertimeGrossPay,0) +
            COALESCE(e.LongevityGrossPay,0) +
            COALESCE(e.PostSeparationGrossPay,0) +
            COALESCE(e.MiscellaneousGrossPay,0)
        ) AS QuarterlySalary
    FROM Earnings e
    JOIN Employee emp ON e.EmployeeID = emp.EmployeeID
    JOIN Calendar c ON e.CalendarID = c.CalendarID
    WHERE c.CalendarYear = @Year
      AND c.Quarter = @Quarter
      AND e.AbsenceID IS NULL   -- Only earning rows
    GROUP BY emp.EmployeeID, emp.FirstName, emp.LastName;
END;
GO


-- Insert 2021 Q1 earnings for testing
INSERT INTO Earnings (
    EmployeeID, CalendarID, AbsenceID,
    OvertimeGrossPay, BaseGrossPay, LongevityGrossPay,
    PostSeparationGrossPay, MiscellaneousGrossPay
)
SELECT 
    1, 
    CalendarID,
    NULL,
    80, 250, 0, 0, 120
FROM Calendar
WHERE CalendarYear = 2021 AND Quarter = 1;

--return earning rows based on year and quarter
SELECT 
    c.CalendarYear,
    c.Quarter,
    COUNT(*) AS EarningsRows
FROM Earnings e
JOIN Calendar c ON e.CalendarID = c.CalendarID
WHERE e.AbsenceID IS NULL     -- only earning rows, same as procedure
GROUP BY c.CalendarYear, c.Quarter
ORDER BY c.CalendarYear, c.Quarter;

SELECT * FROM Calendar;

--show the data for calender year, quarter and count of number of days
SELECT CalendarYear, Quarter, COUNT(*) AS Number_Of_Days
FROM Calendar
GROUP BY CalendarYear, Quarter
ORDER BY CalendarYear, Quarter;

--execution
EXEC sp_Employee_Payroll @Year = 2019, @Quarter = 2;




	

SET STATISTICS IO ON;


--indexing testing 

SELECT * FROM Earnings 
WHERE EmployeeID = 100;


-- Speeds up joins and searches using EmployeeID
CREATE NONCLUSTERED INDEX IX_Earnings_EmployeeID
ON Earnings(EmployeeID);


-----------------------------------------------------------------------------------------------------
--Window functions, CTE, Commit and Subqueries
use Project_Team6

--ranking employees with least absences to show best performance
select e.firstname, count(er.absenceid) as Absences, DENSE_RANK() over (order by count(er.absenceid)) as Rank_by_least_absences
from employee e join earnings er
on e.EmployeeID=er.EmployeeID
group by e.firstname

--Partition by department then rank employees with least absences to show best performance
select e.firstname, d.departmentname, count(er.absenceid) as Absences, 
DENSE_RANK() over (partition by d.departmentname order by count(er.absenceid)) as Rank_by_department
from employee e join earnings er
on e.EmployeeID=er.EmployeeID
join department d on e.departmentid=d.departmentid
group by e.firstname, d.DepartmentName

--RANk departments by least absences
select d.Departmentname, count(er.absenceid) as Total_Absences, DENSE_RANK() over (order by count(er.absenceid)) as Rank_based_on_least_Absences
from employee e join Earnings er on e.EmployeeID=er.employeeid
join Department d on e.DepartmentID=d.DepartmentID
group by d.DepartmentName;

--CTE with Subquery
--create a CTE to find employees and their department who have never been absent

with CTE_Zero_Absence AS(
	select e.firstname, d.departmentname 
	from employee e join  Department d
	on d.DepartmentID=e.DepartmentID
	where e.employeeid IN 
		(select employeeid from earnings where AbsenceID IS NULL)
)
select * from CTE_Zero_Absence;




--commit after inserting a new column of description of reason of absence in the absence table
alter table absence
add Description varchar(200);

begin transaction
go

update absence
set description='None'
where reason=0

update absence
set description='Certain infectious and parasitic diseases'
where reason=1

update absence
set description='Neoplasms'
where reason=2

update absence
set description='Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism'
where reason=3

update absence
set description='Endocrine, nutritional and metabolic diseases'
where reason=4
   
update absence
set description='Mental and behavioural disorders'
where reason=5
  
update absence
set description='Diseases of the nervous system'
where reason=6
  
update absence
set description='Diseases of the eye and adnexa'
where reason=7
   
update absence
set description='Diseases of the ear and mastoid process'
where reason=8
  
update absence
set description='Diseases of the circulatory system'
where reason=9
 
update absence
set description='Diseases of the respiratory system'
where reason=10
  
update absence
set description='Diseases of the digestive system'
where reason=11
  
update absence
set description='Diseases of the skin and subcutaneous tissue'
where reason=12

update absence
set description='Diseases of the musculoskeletal system and connective tissue'
where reason=13
  
update absence
set description='Diseases of the genitourinary system'
where reason=14
 
update absence
set description='Pregnancy, childbirth and the puerperium'
where reason=15
  
update absence
set description='Certain conditions originating in the perinatal period'
where reason=16

update absence
set description='Congenital malformations, deformations and chromosomal abnormalities'
where reason=17
 
update absence
set description='Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified'
where reason=18
  
update absence
set description='Injury, poisoning and certain other consequences of external causes'
where reason=19
 
update absence
set description='External causes of morbidity and mortality'
where reason=20
  
update absence
set description='Factors influencing health status and contact with health services'
where reason=21

update absence
set description='patient follow-up'
where reason=22

update absence
set description='medical consultation'
where reason=23

update absence
set description='blood donation'
where reason=24

update absence
set description='laboratory examination'
where reason=25

update absence
set description='unjustified absence'
where reason=26

update absence
set description='physiotherapy'
where reason=27

update absence
set description='dental consultation'
where reason=28

select * from absence

commit

select * from absence